class TestServer < Sinatra::Base
  get '/concepts/?' do
    <<-EOF
      {  
        "class":["concepts","collection"],
        "properties":{  
          "count":2
        },
        "entities":[  
          {  
            "class":["concepts"],
            "rel":["/rels/concepts"],
            "properties":{  
              "text":"barack obama",
              "category":"PERSON"
            },
            "links":[  
              {  
                "rel":["self"],
                "href":"#{@@url}/concepts/1"
              }
            ]
          },
          {  
            "class":["concepts"],
            "rel":["/rels/concepts"],
            "properties":{  
              "text":"tennessee",
              "category":"LOCATION"
            },
            "links":[  
              {  
                "rel":["self"],
                "href":"#{@@url}/concepts/2"
              }
            ]
          }
        ],
        "links":[  
          {  
            "rel":["self"],
            "href":"#{@@url}/concepts"
          }
        ]
      }
    EOF
  end
end
